export const nav_links =[
    {
        id:1,
        title:'Home',
        link:'/home'
    },
    {
        id:2,
        title:'About',
        link:'/about'
    },
    {
        id:3,
        title:'Cources',
        link:'/cources'
    },{
        id:4,
        title:'Blog',
        link:'/blog'
    },
    {
        id:5,
        title:'Contact',
        link:'/home'
    }
]